name: PHP Init
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: composer install --prefer-dist
    
    - name: Run Test 
    - uses: pxgamer/phpunit-action@master
      with:
        command: indexTest.php
