name: PHP Init
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pxgamer/phpunit-action@master
      with:
        command: indexTest.php
