name: CI/CD
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: composer install --prefer-dist
    
    - name: Run Test 
      uses: pxgamer/phpunit-action@master
      with:
        command: indexTest.php
    
    - name: Remote SSH
      id: remote_ssh
      uses: appleboy/ssh-action@master        
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          sudo su
          cd ../../var/www/html/php_github_action
          ls
          git pull origin master          
          git status
    
    - name: Send mail
      if: steps.remote_ssh.outputs.exit_code == 0
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        body: hai adam proses update web server berhasil di sinkronisasi dengan repository anda
        to: adamilkom00@gmail.com
        from: Github Action
        cc: GithubAction@server.com
        content_type: text/html    
    
