name: CI/CD
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: composer install --prefer-dist
    
    - name: Run Test 
      uses: pxgamer/phpunit-action@master
      with:
        command: indexTest.php
    
    - name: Remote SSH
      id: remote_ssh
      uses: appleboy/ssh-action@master        
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          sudo su
          cd ../../var/www/html/php_github_action
          ls
          git fetch --all
          git reset --hard origin/master 
          
    - name: Rebuild
      uses: php-actions/composer@v5
      with:  
        command: |
          sudo su
          cd ../../var/www/html/php_github_action
          ls
